import {
  Finding,
  ComplianceControl,
  RemediationEvent,
  PostureScoreData,
  TrendDataPoint,
  StatCardData,
} from './types';

// --- Findings ---
export const mockFindings: Finding[] = [
  {
    id: 'FINDING-001',
    severity: 'CRITICAL',
    title: 'S3 Bucket Public Access Enabled',
    description: 'S3 bucket "prod-customer-data" has public access enabled, potentially exposing sensitive customer data to the internet.',
    resourceType: 'AWS::S3::Bucket',
    resourceId: 'arn:aws:s3:::prod-customer-data',
    status: 'ACTIVE',
    complianceFramework: ['CIS', 'SOC2'],
    aiExplanation: 'This S3 bucket has Block Public Access settings disabled, and an overly permissive bucket policy grants s3:GetObject to principal "*". This means anyone on the internet can read objects in this bucket. Given this bucket contains customer PII data based on its naming convention and tags, this represents a critical data exposure risk. Immediate remediation should enable S3 Block Public Access and restrict the bucket policy to known IAM principals only.',
    timestamp: '2026-05-23T14:30:00Z',
    generatorId: 'aws-config/s3-bucket-public-read-prohibited',
  },
  {
    id: 'FINDING-002',
    severity: 'CRITICAL',
    title: 'Root Account MFA Not Enabled',
    description: 'The AWS root account does not have multi-factor authentication (MFA) enabled.',
    resourceType: 'AWS::IAM::User',
    resourceId: 'arn:aws:iam::123456789012:root',
    status: 'ACTIVE',
    complianceFramework: ['CIS', 'SOC2'],
    aiExplanation: 'The root account has unrestricted access to all resources in the AWS account. Without MFA, a compromised password could grant full account access. CIS Benchmark 1.5 requires hardware MFA for root. Enable a virtual or hardware MFA device on the root account immediately and store recovery codes securely.',
    timestamp: '2026-05-23T14:15:00Z',
    generatorId: 'aws-config/root-account-mfa-enabled',
  },
  {
    id: 'FINDING-003',
    severity: 'CRITICAL',
    title: 'RDS Instance Publicly Accessible',
    description: 'RDS instance "prod-main-db" is publicly accessible from the internet.',
    resourceType: 'AWS::RDS::DBInstance',
    resourceId: 'arn:aws:rds:us-east-1:123456789012:db:prod-main-db',
    status: 'ACTIVE',
    complianceFramework: ['CIS', 'SOC2'],
    aiExplanation: 'This RDS instance has PubliclyAccessible set to true and its associated security group allows ingress on port 3306 from 0.0.0.0/0. This creates a direct attack vector for database exploitation. Modify the RDS instance to set PubliclyAccessible to false, restrict security group rules, and access the database through a VPN or bastion host.',
    timestamp: '2026-05-23T13:45:00Z',
    generatorId: 'aws-config/rds-instance-public-access-check',
  },
  {
    id: 'FINDING-004',
    severity: 'CRITICAL',
    title: 'IAM User Access Keys Not Rotated (>90 days)',
    description: 'IAM user "deploy-bot" has access keys that have not been rotated in over 180 days.',
    resourceType: 'AWS::IAM::User',
    resourceId: 'arn:aws:iam::123456789012:user/deploy-bot',
    status: 'ACTIVE',
    complianceFramework: ['CIS'],
    aiExplanation: 'Long-lived access keys increase the window of opportunity for an attacker if keys are compromised. The current access key was created 183 days ago. CIS Benchmark 1.4 recommends rotation every 90 days. Generate new access keys, update all services using them, then deactivate and delete the old keys.',
    timestamp: '2026-05-23T12:00:00Z',
    generatorId: 'aws-config/access-keys-rotated',
  },
  {
    id: 'FINDING-005',
    severity: 'HIGH',
    title: 'Security Group Allows Unrestricted SSH',
    description: 'Security group "sg-0a1b2c3d4e" allows SSH (port 22) access from 0.0.0.0/0.',
    resourceType: 'AWS::EC2::SecurityGroup',
    resourceId: 'arn:aws:ec2:us-east-1:123456789012:security-group/sg-0a1b2c3d4e',
    status: 'ACTIVE',
    complianceFramework: ['CIS', 'SOC2'],
    aiExplanation: 'This security group has an inbound rule allowing TCP port 22 from all IPv4 addresses (0.0.0.0/0). This exposes any associated instances to SSH brute-force attacks. Restrict the source CIDR to your organization\'s IP range or use AWS Systems Manager Session Manager as a more secure alternative.',
    timestamp: '2026-05-23T11:30:00Z',
    generatorId: 'aws-config/restricted-ssh',
  },
  {
    id: 'FINDING-006',
    severity: 'HIGH',
    title: 'CloudTrail Logging Disabled',
    description: 'CloudTrail is not enabled in the us-west-2 region.',
    resourceType: 'AWS::CloudTrail::Trail',
    resourceId: 'arn:aws:cloudtrail:us-west-2:123456789012:trail',
    status: 'ACTIVE',
    complianceFramework: ['CIS', 'SOC2'],
    aiExplanation: 'CloudTrail provides audit logging for API calls in your account. Without it, you lose visibility into who is making changes, making incident investigation nearly impossible. CIS 3.1 requires CloudTrail be enabled in all regions. Create a multi-region trail with log file validation and S3 server-side encryption.',
    timestamp: '2026-05-23T10:15:00Z',
    generatorId: 'aws-config/cloud-trail-enabled',
  },
  {
    id: 'FINDING-007',
    severity: 'HIGH',
    title: 'EBS Volume Not Encrypted',
    description: 'EBS volume "vol-0f1e2d3c4b5a" is not encrypted at rest.',
    resourceType: 'AWS::EC2::Volume',
    resourceId: 'arn:aws:ec2:us-east-1:123456789012:volume/vol-0f1e2d3c4b5a',
    status: 'ACTIVE',
    complianceFramework: ['SOC2'],
    aiExplanation: 'Unencrypted EBS volumes could expose data if the underlying hardware is compromised or the snapshot is shared. Enable default EBS encryption in the account settings and create encrypted copies of existing volumes. Attached instances will need to be stopped briefly during migration.',
    timestamp: '2026-05-23T09:45:00Z',
    generatorId: 'aws-config/encrypted-volumes',
  },
  {
    id: 'FINDING-008',
    severity: 'HIGH',
    title: 'Lambda Function Uses Outdated Runtime',
    description: 'Lambda function "payment-processor" uses Node.js 14.x which is end-of-life.',
    resourceType: 'AWS::Lambda::Function',
    resourceId: 'arn:aws:lambda:us-east-1:123456789012:function:payment-processor',
    status: 'ACTIVE',
    complianceFramework: ['SOC2'],
    aiExplanation: 'Node.js 14.x reached end-of-life and no longer receives security patches. Running production workloads on deprecated runtimes exposes you to known vulnerabilities. Upgrade to Node.js 20.x or later, test thoroughly in staging, and redeploy. Update any incompatible dependencies first.',
    timestamp: '2026-05-23T09:00:00Z',
    generatorId: 'aws-config/lambda-function-settings-check',
  },
  {
    id: 'FINDING-009',
    severity: 'HIGH',
    title: 'IAM Policy Allows Full Admin Access',
    description: 'IAM role "dev-team-role" has AdministratorAccess policy attached.',
    resourceType: 'AWS::IAM::Role',
    resourceId: 'arn:aws:iam::123456789012:role/dev-team-role',
    status: 'ACTIVE',
    complianceFramework: ['CIS', 'SOC2'],
    aiExplanation: 'The AdministratorAccess managed policy grants unrestricted access to all AWS services and resources. This violates the principle of least privilege. Create a custom policy scoped to only the services and actions the dev team actually needs. Use IAM Access Analyzer to identify the minimum required permissions.',
    timestamp: '2026-05-23T08:30:00Z',
    generatorId: 'aws-config/iam-policy-no-statements-with-admin-access',
  },
  {
    id: 'FINDING-010',
    severity: 'HIGH',
    title: 'VPC Flow Logs Not Enabled',
    description: 'VPC "vpc-0abc123def" does not have flow logs enabled.',
    resourceType: 'AWS::EC2::VPC',
    resourceId: 'arn:aws:ec2:us-east-1:123456789012:vpc/vpc-0abc123def',
    status: 'ACTIVE',
    complianceFramework: ['CIS'],
    aiExplanation: 'VPC Flow Logs capture network traffic metadata, essential for threat detection and forensic analysis. Enable flow logs on this VPC, sending to CloudWatch Logs or S3 with at least 30-day retention. Use REJECT-only logging if cost is a concern, though ALL traffic is recommended.',
    timestamp: '2026-05-22T18:00:00Z',
    generatorId: 'aws-config/vpc-flow-logs-enabled',
  },
  {
    id: 'FINDING-011',
    severity: 'MEDIUM',
    title: 'S3 Bucket Versioning Not Enabled',
    description: 'S3 bucket "app-config-store" does not have versioning enabled.',
    resourceType: 'AWS::S3::Bucket',
    resourceId: 'arn:aws:s3:::app-config-store',
    status: 'ACTIVE',
    complianceFramework: ['CIS'],
    aiExplanation: 'Without versioning, accidental deletion or overwriting of objects is irreversible. Enabling versioning provides an additional layer of data protection and is required by CIS 2.1.1. Enable versioning and consider adding lifecycle rules to manage version costs.',
    timestamp: '2026-05-22T16:30:00Z',
    generatorId: 'aws-config/s3-bucket-versioning-enabled',
  },
  {
    id: 'FINDING-012',
    severity: 'MEDIUM',
    title: 'SNS Topic Not Encrypted',
    description: 'SNS topic "order-notifications" is not using server-side encryption.',
    resourceType: 'AWS::SNS::Topic',
    resourceId: 'arn:aws:sns:us-east-1:123456789012:order-notifications',
    status: 'ACTIVE',
    complianceFramework: ['SOC2'],
    aiExplanation: 'Messages published to this SNS topic are stored unencrypted at rest. If the topic handles sensitive data like order details, this could lead to exposure. Enable SSE using an AWS KMS key to encrypt message contents at rest.',
    timestamp: '2026-05-22T15:00:00Z',
    generatorId: 'aws-config/sns-encrypted-kms',
  },
  {
    id: 'FINDING-013',
    severity: 'MEDIUM',
    title: 'EC2 Instance Without IMDSv2',
    description: 'EC2 instance "i-0a1b2c3d4e5f" is not configured to require IMDSv2.',
    resourceType: 'AWS::EC2::Instance',
    resourceId: 'arn:aws:ec2:us-east-1:123456789012:instance/i-0a1b2c3d4e5f',
    status: 'ACTIVE',
    complianceFramework: ['CIS'],
    aiExplanation: 'IMDSv1 is vulnerable to SSRF attacks that can steal instance credentials. IMDSv2 uses session-based tokens that mitigate this. Modify the instance metadata options to set HttpTokens to "required", enforcing IMDSv2 for all metadata requests.',
    timestamp: '2026-05-22T14:00:00Z',
    generatorId: 'aws-config/ec2-imdsv2-check',
  },
  {
    id: 'FINDING-014',
    severity: 'MEDIUM',
    title: 'ElastiCache Redis Without Encryption in Transit',
    description: 'ElastiCache Redis cluster "session-cache" does not have encryption in transit enabled.',
    resourceType: 'AWS::ElastiCache::ReplicationGroup',
    resourceId: 'arn:aws:elasticache:us-east-1:123456789012:replicationgroup:session-cache',
    status: 'ACTIVE',
    complianceFramework: ['SOC2'],
    aiExplanation: 'Without TLS, data traveling between your application and Redis is sent in plaintext, making it vulnerable to network sniffing. Enable in-transit encryption by modifying the replication group. Note: this requires a brief downtime as the cluster needs to be recreated.',
    timestamp: '2026-05-22T12:30:00Z',
    generatorId: 'aws-config/elasticache-repl-grp-encrypted-in-transit',
  },
  {
    id: 'FINDING-015',
    severity: 'MEDIUM',
    title: 'CloudWatch Log Group Without Retention Policy',
    description: 'Log group "/aws/lambda/user-auth" has no retention policy set (infinite retention).',
    resourceType: 'AWS::Logs::LogGroup',
    resourceId: 'arn:aws:logs:us-east-1:123456789012:log-group:/aws/lambda/user-auth',
    status: 'ACTIVE',
    complianceFramework: ['SOC2'],
    aiExplanation: 'Infinite log retention leads to unbounded storage costs and potential data compliance issues. Set a retention policy (e.g., 90 or 365 days) based on your audit requirements. For compliance, ensure minimum retention meets SOC 2 requirements before reducing.',
    timestamp: '2026-05-22T11:00:00Z',
    generatorId: 'aws-config/cw-loggroup-retention-period-check',
  },
  {
    id: 'FINDING-016',
    severity: 'MEDIUM',
    title: 'DynamoDB Table Without Point-in-Time Recovery',
    description: 'DynamoDB table "user-sessions" does not have PITR enabled.',
    resourceType: 'AWS::DynamoDB::Table',
    resourceId: 'arn:aws:dynamodb:us-east-1:123456789012:table/user-sessions',
    status: 'ACTIVE',
    complianceFramework: ['SOC2'],
    aiExplanation: 'Without Point-in-Time Recovery, you cannot restore the table to any second in the last 35 days. This is critical for disaster recovery. Enable PITR via the console or CLI — it has no impact on table performance.',
    timestamp: '2026-05-22T10:15:00Z',
    generatorId: 'aws-config/dynamodb-pitr-enabled',
  },
  {
    id: 'FINDING-017',
    severity: 'MEDIUM',
    title: 'ALB Access Logging Disabled',
    description: 'Application Load Balancer "prod-web-alb" does not have access logging enabled.',
    resourceType: 'AWS::ElasticLoadBalancingV2::LoadBalancer',
    resourceId: 'arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/prod-web-alb/1a2b3c4d',
    status: 'ACTIVE',
    complianceFramework: ['CIS'],
    aiExplanation: 'Access logs capture detailed information about requests, crucial for security analysis and compliance auditing. Enable access logging and configure the S3 bucket with appropriate permissions. Expect approximately 1-5 GB of logs per day for a moderately trafficked ALB.',
    timestamp: '2026-05-22T09:00:00Z',
    generatorId: 'aws-config/elb-logging-enabled',
  },
  {
    id: 'FINDING-018',
    severity: 'LOW',
    title: 'S3 Bucket Without Lifecycle Policy',
    description: 'S3 bucket "application-logs-archive" has no lifecycle policy configured.',
    resourceType: 'AWS::S3::Bucket',
    resourceId: 'arn:aws:s3:::application-logs-archive',
    status: 'ACTIVE',
    complianceFramework: ['SOC2'],
    aiExplanation: 'Without lifecycle policies, objects remain in the same storage class indefinitely, leading to unnecessary costs. Implement lifecycle rules to transition older objects to S3 Glacier and eventually expire them based on retention requirements.',
    timestamp: '2026-05-22T08:00:00Z',
    generatorId: 'aws-config/s3-lifecycle-policy-check',
  },
  {
    id: 'FINDING-019',
    severity: 'LOW',
    title: 'IAM Password Policy Insufficient Complexity',
    description: 'Account password policy does not require symbols in passwords.',
    resourceType: 'AWS::IAM::AccountPasswordPolicy',
    resourceId: 'arn:aws:iam::123456789012:account-password-policy',
    status: 'ACTIVE',
    complianceFramework: ['CIS'],
    aiExplanation: 'CIS 1.8 recommends requiring at least one symbol in IAM user passwords. Update the account password policy to require symbols, uppercase, lowercase, and numbers with a minimum length of 14 characters.',
    timestamp: '2026-05-21T18:00:00Z',
    generatorId: 'aws-config/iam-password-policy',
  },
  {
    id: 'FINDING-020',
    severity: 'LOW',
    title: 'EC2 Instance Tagging Non-Compliant',
    description: 'EC2 instance "i-9f8e7d6c5b" is missing required tags: Environment, Owner, CostCenter.',
    resourceType: 'AWS::EC2::Instance',
    resourceId: 'arn:aws:ec2:us-east-1:123456789012:instance/i-9f8e7d6c5b',
    status: 'ACTIVE',
    complianceFramework: ['SOC2'],
    aiExplanation: 'Proper tagging is essential for cost allocation, access control, and operational management. Add the required tags (Environment, Owner, CostCenter) to this instance. Consider implementing AWS Organizations tag policies to enforce compliance.',
    timestamp: '2026-05-21T16:00:00Z',
    generatorId: 'aws-config/required-tags',
  },
  {
    id: 'FINDING-021',
    severity: 'LOW',
    title: 'GuardDuty Not Enabled in Region',
    description: 'Amazon GuardDuty is not enabled in ap-southeast-1.',
    resourceType: 'AWS::GuardDuty::Detector',
    resourceId: 'arn:aws:guardduty:ap-southeast-1:123456789012:detector',
    status: 'ACTIVE',
    complianceFramework: ['CIS'],
    aiExplanation: 'GuardDuty provides intelligent threat detection by analyzing CloudTrail, VPC Flow Logs, and DNS logs. Enable it in all regions used by your organization for comprehensive coverage. The free trial gives 30 days to evaluate costs.',
    timestamp: '2026-05-21T14:00:00Z',
    generatorId: 'aws-config/guardduty-enabled-centralized',
  },
  {
    id: 'FINDING-022',
    severity: 'HIGH',
    title: 'KMS Key Rotation Not Enabled',
    description: 'KMS key "alias/app-encryption" does not have automatic key rotation enabled.',
    resourceType: 'AWS::KMS::Key',
    resourceId: 'arn:aws:kms:us-east-1:123456789012:key/a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    status: 'ACTIVE',
    complianceFramework: ['CIS', 'SOC2'],
    aiExplanation: 'Automatic annual key rotation limits the amount of data encrypted under a single key version, reducing blast radius if a key is compromised. Enable automatic rotation — AWS manages the key material rotation without requiring changes to your application code.',
    timestamp: '2026-05-22T07:00:00Z',
    generatorId: 'aws-config/kms-cmk-rotation-enabled',
  },
  {
    id: 'FINDING-023',
    severity: 'LOW',
    title: 'Default VPC In Use',
    description: 'Resources are deployed in the default VPC in us-east-1.',
    resourceType: 'AWS::EC2::VPC',
    resourceId: 'arn:aws:ec2:us-east-1:123456789012:vpc/vpc-default',
    status: 'ACTIVE',
    complianceFramework: ['CIS'],
    aiExplanation: 'Default VPCs have overly permissive network configurations including public subnets and internet gateways. Migrate resources to custom VPCs with properly segmented subnets, restricted security groups, and NACLs that follow your security architecture.',
    timestamp: '2026-05-21T12:00:00Z',
    generatorId: 'aws-config/ec2-default-vpc',
  },
  {
    id: 'FINDING-024',
    severity: 'MEDIUM',
    title: 'RDS Automated Backups Retention Too Short',
    description: 'RDS instance "analytics-db" has backup retention set to only 1 day.',
    resourceType: 'AWS::RDS::DBInstance',
    resourceId: 'arn:aws:rds:us-east-1:123456789012:db:analytics-db',
    status: 'ACTIVE',
    complianceFramework: ['SOC2'],
    aiExplanation: 'A 1-day backup retention window severely limits your recovery options. Increase the retention period to at least 7 days (14-35 recommended for production). This change can be applied without downtime during the next maintenance window.',
    timestamp: '2026-05-22T06:00:00Z',
    generatorId: 'aws-config/rds-backup-retention',
  },
  {
    id: 'FINDING-025',
    severity: 'CRITICAL',
    title: 'Secrets Manager Secret Not Rotated',
    description: 'Secret "prod/database/master-credentials" has not been rotated in 120 days.',
    resourceType: 'AWS::SecretsManager::Secret',
    resourceId: 'arn:aws:secretsmanager:us-east-1:123456789012:secret:prod/database/master-credentials',
    status: 'ACTIVE',
    complianceFramework: ['CIS', 'SOC2'],
    aiExplanation: 'Database credentials that haven\'t been rotated in 120 days pose a significant risk. Configure automatic rotation using a Lambda rotation function. Secrets Manager provides templates for RDS, Redshift, and DocumentDB that handle the rotation logic automatically.',
    timestamp: '2026-05-23T07:00:00Z',
    generatorId: 'aws-config/secretsmanager-scheduled-rotation-success-check',
  },
  {
    id: 'FINDING-026',
    severity: 'HIGH',
    title: 'WAF Not Associated with ALB',
    description: 'Application Load Balancer "api-gateway-alb" has no AWS WAF web ACL associated.',
    resourceType: 'AWS::ElasticLoadBalancingV2::LoadBalancer',
    resourceId: 'arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/api-gateway-alb/5e6f7g8h',
    status: 'ACTIVE',
    complianceFramework: ['SOC2'],
    aiExplanation: 'Without WAF protection, the ALB is exposed to common web attacks like SQL injection, XSS, and DDoS. Associate an AWS WAF web ACL with managed rule groups (AWSManagedRulesCommonRuleSet, AWSManagedRulesSQLiRuleSet) to provide baseline protection.',
    timestamp: '2026-05-22T05:00:00Z',
    generatorId: 'aws-config/alb-waf-enabled',
  },
  {
    id: 'FINDING-027',
    severity: 'MEDIUM',
    title: 'ECR Image Scan Findings',
    description: 'ECR repository "app/backend" has container images with known vulnerabilities.',
    resourceType: 'AWS::ECR::Repository',
    resourceId: 'arn:aws:ecr:us-east-1:123456789012:repository/app/backend',
    status: 'ACTIVE',
    complianceFramework: ['SOC2'],
    aiExplanation: 'The latest image scan found 3 high and 12 medium vulnerabilities in base image dependencies. Update the base image to the latest patched version, run npm audit fix for Node.js dependencies, and enable scan-on-push to catch future vulnerabilities early.',
    timestamp: '2026-05-22T04:00:00Z',
    generatorId: 'aws-config/ecr-image-scan-findings',
  },
  {
    id: 'FINDING-028',
    severity: 'LOW',
    title: 'CloudFormation Stack Drift Detected',
    description: 'CloudFormation stack "prod-infrastructure" has drifted from its template.',
    resourceType: 'AWS::CloudFormation::Stack',
    resourceId: 'arn:aws:cloudformation:us-east-1:123456789012:stack/prod-infrastructure',
    status: 'ACTIVE',
    complianceFramework: ['SOC2'],
    aiExplanation: 'Stack drift means resources have been modified outside of CloudFormation, creating inconsistency between your template and actual infrastructure. Run drift detection, review changes, and either update the template to match or revert manual changes to maintain infrastructure-as-code compliance.',
    timestamp: '2026-05-21T10:00:00Z',
    generatorId: 'aws-config/cloudformation-stack-drift-detection-check',
  },
  {
    id: 'FINDING-029',
    severity: 'MEDIUM',
    title: 'SQS Queue Without Server-Side Encryption',
    description: 'SQS queue "payment-processing-queue" does not have SSE enabled.',
    resourceType: 'AWS::SQS::Queue',
    resourceId: 'arn:aws:sqs:us-east-1:123456789012:payment-processing-queue',
    status: 'ACTIVE',
    complianceFramework: ['SOC2'],
    aiExplanation: 'Messages in this SQS queue containing payment data are stored unencrypted. Enable SSE-SQS (free) or SSE-KMS for additional key management controls. This change takes effect immediately without impacting message producers or consumers.',
    timestamp: '2026-05-22T03:00:00Z',
    generatorId: 'aws-config/sqs-queue-encrypted',
  },
  {
    id: 'FINDING-030',
    severity: 'HIGH',
    title: 'Elasticsearch Domain Without Encryption',
    description: 'Elasticsearch domain "search-prod" does not have encryption at rest enabled.',
    resourceType: 'AWS::Elasticsearch::Domain',
    resourceId: 'arn:aws:es:us-east-1:123456789012:domain/search-prod',
    status: 'ACTIVE',
    complianceFramework: ['SOC2'],
    aiExplanation: 'Search indices may contain sensitive data extracted from application databases. Enable encryption at rest using AWS KMS. Note: enabling encryption requires creating a new domain and reindexing data, so plan for migration downtime.',
    timestamp: '2026-05-22T02:00:00Z',
    generatorId: 'aws-config/elasticsearch-encrypted-at-rest',
  },
  {
    id: 'FINDING-031',
    severity: 'LOW',
    title: 'S3 Bucket Logging Not Enabled',
    description: 'S3 bucket "static-assets-cdn" does not have server access logging enabled.',
    resourceType: 'AWS::S3::Bucket',
    resourceId: 'arn:aws:s3:::static-assets-cdn',
    status: 'RESOLVED',
    complianceFramework: ['CIS'],
    aiExplanation: 'Server access logging provides detailed records of requests made to the bucket, useful for security auditing and access analysis. Enable logging with a separate logging bucket to avoid recursive log creation.',
    timestamp: '2026-05-20T14:00:00Z',
    generatorId: 'aws-config/s3-bucket-logging-enabled',
  },
  {
    id: 'FINDING-032',
    severity: 'MEDIUM',
    title: 'ECS Task Definition Uses Host Network Mode',
    description: 'ECS task definition "api-service" uses host network mode, sharing the host network namespace.',
    resourceType: 'AWS::ECS::TaskDefinition',
    resourceId: 'arn:aws:ecs:us-east-1:123456789012:task-definition/api-service:14',
    status: 'ACTIVE',
    complianceFramework: ['SOC2'],
    aiExplanation: 'Host network mode gives the container direct access to the host EC2 instance network interfaces, reducing isolation. Switch to awsvpc network mode for better security isolation, which also enables security groups per task and simplifies networking.',
    timestamp: '2026-05-21T22:00:00Z',
    generatorId: 'aws-config/ecs-task-definition-network-mode',
  },
];

// --- CIS Benchmark Controls ---
export const mockCISControls: ComplianceControl[] = [
  { controlId: 'CIS 1.1', framework: 'CIS', category: 'Identity & Access Management', description: 'Maintain current contact details', status: 'PASS', relatedRules: ['contact-details-check'], resourcesAffected: 0 },
  { controlId: 'CIS 1.2', framework: 'CIS', category: 'Identity & Access Management', description: 'Ensure security contact information is registered', status: 'PASS', relatedRules: ['security-contact-check'], resourcesAffected: 0 },
  { controlId: 'CIS 1.3', framework: 'CIS', category: 'Identity & Access Management', description: 'Ensure security questions are registered', status: 'PASS', relatedRules: ['security-questions-check'], resourcesAffected: 0 },
  { controlId: 'CIS 1.4', framework: 'CIS', category: 'Identity & Access Management', description: 'Ensure access keys are rotated every 90 days', status: 'FAIL', relatedRules: ['access-keys-rotated'], resourcesAffected: 3 },
  { controlId: 'CIS 1.5', framework: 'CIS', category: 'Identity & Access Management', description: 'Ensure MFA is enabled for root account', status: 'FAIL', relatedRules: ['root-account-mfa-enabled'], resourcesAffected: 1 },
  { controlId: 'CIS 1.6', framework: 'CIS', category: 'Identity & Access Management', description: 'Ensure hardware MFA is enabled for root account', status: 'FAIL', relatedRules: ['root-account-hardware-mfa-enabled'], resourcesAffected: 1 },
  { controlId: 'CIS 1.7', framework: 'CIS', category: 'Identity & Access Management', description: 'Eliminate use of root account', status: 'PASS', relatedRules: ['root-account-usage'], resourcesAffected: 0 },
  { controlId: 'CIS 1.8', framework: 'CIS', category: 'Identity & Access Management', description: 'Ensure IAM password policy requires symbols', status: 'FAIL', relatedRules: ['iam-password-policy'], resourcesAffected: 1 },
  { controlId: 'CIS 1.9', framework: 'CIS', category: 'Identity & Access Management', description: 'Ensure IAM password policy prevents password reuse', status: 'PASS', relatedRules: ['iam-password-policy-reuse'], resourcesAffected: 0 },
  { controlId: 'CIS 1.10', framework: 'CIS', category: 'Identity & Access Management', description: 'Ensure MFA is enabled for all IAM users with console access', status: 'PASS', relatedRules: ['mfa-enabled-for-iam-console-access'], resourcesAffected: 0 },
  { controlId: 'CIS 2.1', framework: 'CIS', category: 'Storage', description: 'Ensure S3 bucket versioning is enabled', status: 'FAIL', relatedRules: ['s3-bucket-versioning-enabled'], resourcesAffected: 4 },
  { controlId: 'CIS 2.2', framework: 'CIS', category: 'Storage', description: 'Ensure S3 bucket public access is blocked', status: 'FAIL', relatedRules: ['s3-bucket-public-read-prohibited'], resourcesAffected: 1 },
  { controlId: 'CIS 2.3', framework: 'CIS', category: 'Storage', description: 'Ensure EBS volumes are encrypted', status: 'FAIL', relatedRules: ['encrypted-volumes'], resourcesAffected: 2 },
  { controlId: 'CIS 2.4', framework: 'CIS', category: 'Storage', description: 'Ensure S3 bucket logging is enabled', status: 'PASS', relatedRules: ['s3-bucket-logging-enabled'], resourcesAffected: 0 },
  { controlId: 'CIS 3.1', framework: 'CIS', category: 'Logging & Monitoring', description: 'Ensure CloudTrail is enabled in all regions', status: 'FAIL', relatedRules: ['cloud-trail-enabled'], resourcesAffected: 1 },
  { controlId: 'CIS 3.2', framework: 'CIS', category: 'Logging & Monitoring', description: 'Ensure CloudTrail log file validation is enabled', status: 'PASS', relatedRules: ['cloud-trail-log-file-validation-enabled'], resourcesAffected: 0 },
  { controlId: 'CIS 3.3', framework: 'CIS', category: 'Logging & Monitoring', description: 'Ensure VPC flow logs are enabled', status: 'FAIL', relatedRules: ['vpc-flow-logs-enabled'], resourcesAffected: 2 },
  { controlId: 'CIS 3.4', framework: 'CIS', category: 'Logging & Monitoring', description: 'Ensure GuardDuty is enabled', status: 'FAIL', relatedRules: ['guardduty-enabled-centralized'], resourcesAffected: 1 },
  { controlId: 'CIS 4.1', framework: 'CIS', category: 'Networking', description: 'Ensure no security groups allow SSH from 0.0.0.0/0', status: 'FAIL', relatedRules: ['restricted-ssh'], resourcesAffected: 3 },
  { controlId: 'CIS 4.2', framework: 'CIS', category: 'Networking', description: 'Ensure no security groups allow RDP from 0.0.0.0/0', status: 'PASS', relatedRules: ['restricted-rdp'], resourcesAffected: 0 },
  { controlId: 'CIS 4.3', framework: 'CIS', category: 'Networking', description: 'Ensure default VPC is not used', status: 'FAIL', relatedRules: ['ec2-default-vpc'], resourcesAffected: 5 },
  { controlId: 'CIS 5.1', framework: 'CIS', category: 'Encryption', description: 'Ensure KMS key rotation is enabled', status: 'FAIL', relatedRules: ['kms-cmk-rotation-enabled'], resourcesAffected: 2 },
];

// --- SOC 2 Controls ---
export const mockSOC2Controls: ComplianceControl[] = [
  { controlId: 'CC6.1', framework: 'SOC2', category: 'Logical & Physical Access', description: 'Implement logical access security over protected information assets', status: 'FAIL', relatedRules: ['iam-policy-no-statements-with-admin-access', 'restricted-ssh'], resourcesAffected: 4 },
  { controlId: 'CC6.2', framework: 'SOC2', category: 'Logical & Physical Access', description: 'Prior to issuing system credentials, register and authorize new users', status: 'PASS', relatedRules: ['iam-user-mfa-enabled'], resourcesAffected: 0 },
  { controlId: 'CC6.3', framework: 'SOC2', category: 'Logical & Physical Access', description: 'Authorize, modify, or remove access based on roles', status: 'FAIL', relatedRules: ['iam-policy-no-statements-with-admin-access'], resourcesAffected: 2 },
  { controlId: 'CC6.6', framework: 'SOC2', category: 'Logical & Physical Access', description: 'Restrict system access through network security controls', status: 'FAIL', relatedRules: ['restricted-ssh', 'rds-instance-public-access-check'], resourcesAffected: 3 },
  { controlId: 'CC6.7', framework: 'SOC2', category: 'Logical & Physical Access', description: 'Restrict transmission of data to authorized parties', status: 'PASS', relatedRules: ['s3-bucket-ssl-requests-only'], resourcesAffected: 0 },
  { controlId: 'CC7.1', framework: 'SOC2', category: 'System Operations', description: 'Detect and monitor security vulnerabilities and threats', status: 'FAIL', relatedRules: ['guardduty-enabled-centralized', 'ecr-image-scan-findings'], resourcesAffected: 2 },
  { controlId: 'CC7.2', framework: 'SOC2', category: 'System Operations', description: 'Monitor system components for anomalies', status: 'PASS', relatedRules: ['cloudwatch-alarm-configured'], resourcesAffected: 0 },
  { controlId: 'CC7.3', framework: 'SOC2', category: 'System Operations', description: 'Evaluate security events to determine impact', status: 'PASS', relatedRules: ['security-hub-enabled'], resourcesAffected: 0 },
  { controlId: 'CC8.1', framework: 'SOC2', category: 'Change Management', description: 'Authorize, design, develop, configure, document, test, approve, and implement changes', status: 'FAIL', relatedRules: ['cloudformation-stack-drift-detection-check'], resourcesAffected: 1 },
  { controlId: 'A1.1', framework: 'SOC2', category: 'Availability', description: 'Maintain processing capacity to meet availability commitments', status: 'PASS', relatedRules: ['autoscaling-group-elb-healthcheck-required'], resourcesAffected: 0 },
  { controlId: 'A1.2', framework: 'SOC2', category: 'Availability', description: 'Provide for recovery of data to meet availability commitments', status: 'FAIL', relatedRules: ['dynamodb-pitr-enabled', 'rds-backup-retention'], resourcesAffected: 2 },
  { controlId: 'C1.1', framework: 'SOC2', category: 'Confidentiality', description: 'Identify and maintain confidential information', status: 'FAIL', relatedRules: ['s3-bucket-public-read-prohibited', 'encrypted-volumes'], resourcesAffected: 3 },
  { controlId: 'C1.2', framework: 'SOC2', category: 'Confidentiality', description: 'Dispose of confidential information in accordance with policy', status: 'PASS', relatedRules: ['s3-lifecycle-policy-check'], resourcesAffected: 0 },
  { controlId: 'PI1.1', framework: 'SOC2', category: 'Processing Integrity', description: 'Implement quality controls on processing', status: 'PASS', relatedRules: ['lambda-function-settings-check'], resourcesAffected: 0 },
  { controlId: 'P1.1', framework: 'SOC2', category: 'Privacy', description: 'Communicate privacy commitments to data subjects', status: 'PASS', relatedRules: ['privacy-policy-check'], resourcesAffected: 0 },
  { controlId: 'CC9.1', framework: 'SOC2', category: 'Risk Mitigation', description: 'Identify and assess risks to system security', status: 'PASS', relatedRules: ['security-hub-enabled'], resourcesAffected: 0 },
];

// --- Remediation Events ---
export const mockRemediationEvents: RemediationEvent[] = [
  {
    id: 'REM-001',
    findingId: 'FINDING-031',
    resourceId: 'arn:aws:s3:::static-assets-cdn',
    resourceType: 'AWS::S3::Bucket',
    actionTaken: 'Enabled S3 server access logging to s3://logging-bucket/static-assets-cdn/',
    beforeState: '{"LoggingEnabled": false}',
    afterState: '{"LoggingEnabled": true, "TargetBucket": "logging-bucket", "TargetPrefix": "static-assets-cdn/"}',
    autoRemediated: true,
    timestamp: '2026-05-23T14:25:00Z',
    success: true,
  },
  {
    id: 'REM-002',
    findingId: 'FINDING-005',
    resourceId: 'arn:aws:ec2:us-east-1:123456789012:security-group/sg-0a1b2c3d4e',
    resourceType: 'AWS::EC2::SecurityGroup',
    actionTaken: 'Restricted SSH access from 0.0.0.0/0 to corporate CIDR 10.0.0.0/8',
    beforeState: '{"IpProtocol": "tcp", "FromPort": 22, "ToPort": 22, "CidrIp": "0.0.0.0/0"}',
    afterState: '{"IpProtocol": "tcp", "FromPort": 22, "ToPort": 22, "CidrIp": "10.0.0.0/8"}',
    autoRemediated: true,
    timestamp: '2026-05-23T13:50:00Z',
    success: true,
  },
  {
    id: 'REM-003',
    findingId: 'FINDING-007',
    resourceId: 'arn:aws:ec2:us-east-1:123456789012:volume/vol-0f1e2d3c4b5a',
    resourceType: 'AWS::EC2::Volume',
    actionTaken: 'Created encrypted copy of volume and replaced the unencrypted volume',
    beforeState: '{"Encrypted": false, "VolumeId": "vol-0f1e2d3c4b5a"}',
    afterState: '{"Encrypted": true, "KmsKeyId": "alias/aws/ebs", "VolumeId": "vol-new-encrypted"}',
    autoRemediated: false,
    timestamp: '2026-05-23T12:30:00Z',
    success: true,
  },
  {
    id: 'REM-004',
    findingId: 'FINDING-011',
    resourceId: 'arn:aws:s3:::app-config-store',
    resourceType: 'AWS::S3::Bucket',
    actionTaken: 'Enabled versioning on S3 bucket',
    beforeState: '{"Versioning": "Disabled"}',
    afterState: '{"Versioning": "Enabled"}',
    autoRemediated: true,
    timestamp: '2026-05-23T11:15:00Z',
    success: true,
  },
  {
    id: 'REM-005',
    findingId: 'FINDING-015',
    resourceId: 'arn:aws:logs:us-east-1:123456789012:log-group:/aws/lambda/user-auth',
    resourceType: 'AWS::Logs::LogGroup',
    actionTaken: 'Set retention policy to 90 days',
    beforeState: '{"RetentionInDays": null}',
    afterState: '{"RetentionInDays": 90}',
    autoRemediated: true,
    timestamp: '2026-05-23T10:00:00Z',
    success: true,
  },
  {
    id: 'REM-006',
    findingId: 'FINDING-019',
    resourceId: 'arn:aws:iam::123456789012:account-password-policy',
    resourceType: 'AWS::IAM::AccountPasswordPolicy',
    actionTaken: 'Updated password policy to require symbols and minimum length of 14',
    beforeState: '{"RequireSymbols": false, "MinimumPasswordLength": 8}',
    afterState: '{"RequireSymbols": true, "MinimumPasswordLength": 14}',
    autoRemediated: false,
    timestamp: '2026-05-23T09:30:00Z',
    success: true,
  },
  {
    id: 'REM-007',
    findingId: 'FINDING-016',
    resourceId: 'arn:aws:dynamodb:us-east-1:123456789012:table/user-sessions',
    resourceType: 'AWS::DynamoDB::Table',
    actionTaken: 'Enabled Point-in-Time Recovery (PITR)',
    beforeState: '{"PointInTimeRecoveryStatus": "DISABLED"}',
    afterState: '{"PointInTimeRecoveryStatus": "ENABLED"}',
    autoRemediated: true,
    timestamp: '2026-05-23T08:45:00Z',
    success: true,
  },
  {
    id: 'REM-008',
    findingId: 'FINDING-013',
    resourceId: 'arn:aws:ec2:us-east-1:123456789012:instance/i-0a1b2c3d4e5f',
    resourceType: 'AWS::EC2::Instance',
    actionTaken: 'Enforced IMDSv2 by setting HttpTokens to required',
    beforeState: '{"HttpTokens": "optional", "HttpEndpoint": "enabled"}',
    afterState: '{"HttpTokens": "required", "HttpEndpoint": "enabled"}',
    autoRemediated: true,
    timestamp: '2026-05-23T07:30:00Z',
    success: true,
  },
  {
    id: 'REM-009',
    findingId: 'FINDING-003',
    resourceId: 'arn:aws:rds:us-east-1:123456789012:db:prod-main-db',
    resourceType: 'AWS::RDS::DBInstance',
    actionTaken: 'Attempted to disable public accessibility — requires manual approval for production DB',
    beforeState: '{"PubliclyAccessible": true}',
    afterState: '{"PubliclyAccessible": true, "PendingModification": true}',
    autoRemediated: false,
    timestamp: '2026-05-23T06:00:00Z',
    success: false,
  },
  {
    id: 'REM-010',
    findingId: 'FINDING-017',
    resourceId: 'arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/prod-web-alb/1a2b3c4d',
    resourceType: 'AWS::ElasticLoadBalancingV2::LoadBalancer',
    actionTaken: 'Enabled access logging to s3://alb-logs-bucket/prod-web-alb/',
    beforeState: '{"AccessLogsEnabled": false}',
    afterState: '{"AccessLogsEnabled": true, "S3BucketName": "alb-logs-bucket"}',
    autoRemediated: true,
    timestamp: '2026-05-22T22:00:00Z',
    success: true,
  },
  {
    id: 'REM-011',
    findingId: 'FINDING-022',
    resourceId: 'arn:aws:kms:us-east-1:123456789012:key/a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    resourceType: 'AWS::KMS::Key',
    actionTaken: 'Enabled automatic annual key rotation',
    beforeState: '{"KeyRotationEnabled": false}',
    afterState: '{"KeyRotationEnabled": true}',
    autoRemediated: true,
    timestamp: '2026-05-22T20:00:00Z',
    success: true,
  },
  {
    id: 'REM-012',
    findingId: 'FINDING-012',
    resourceId: 'arn:aws:sns:us-east-1:123456789012:order-notifications',
    resourceType: 'AWS::SNS::Topic',
    actionTaken: 'Enabled server-side encryption with AWS-managed KMS key',
    beforeState: '{"KmsMasterKeyId": null}',
    afterState: '{"KmsMasterKeyId": "alias/aws/sns"}',
    autoRemediated: true,
    timestamp: '2026-05-22T18:30:00Z',
    success: true,
  },
  {
    id: 'REM-013',
    findingId: 'FINDING-008',
    resourceId: 'arn:aws:lambda:us-east-1:123456789012:function:payment-processor',
    resourceType: 'AWS::Lambda::Function',
    actionTaken: 'Initiated runtime upgrade from Node.js 14.x to Node.js 20.x — pending deployment review',
    beforeState: '{"Runtime": "nodejs14.x"}',
    afterState: '{"Runtime": "nodejs14.x", "PendingUpgrade": "nodejs20.x"}',
    autoRemediated: false,
    timestamp: '2026-05-22T16:00:00Z',
    success: false,
  },
  {
    id: 'REM-014',
    findingId: 'FINDING-029',
    resourceId: 'arn:aws:sqs:us-east-1:123456789012:payment-processing-queue',
    resourceType: 'AWS::SQS::Queue',
    actionTaken: 'Enabled SSE-SQS encryption on queue',
    beforeState: '{"SqsManagedSseEnabled": false}',
    afterState: '{"SqsManagedSseEnabled": true}',
    autoRemediated: true,
    timestamp: '2026-05-22T14:00:00Z',
    success: true,
  },
  {
    id: 'REM-015',
    findingId: 'FINDING-020',
    resourceId: 'arn:aws:ec2:us-east-1:123456789012:instance/i-9f8e7d6c5b',
    resourceType: 'AWS::EC2::Instance',
    actionTaken: 'Applied required tags: Environment=production, Owner=platform-team, CostCenter=CC-4521',
    beforeState: '{"Tags": [{"Key": "Name", "Value": "api-worker-3"}]}',
    afterState: '{"Tags": [{"Key": "Name", "Value": "api-worker-3"}, {"Key": "Environment", "Value": "production"}, {"Key": "Owner", "Value": "platform-team"}, {"Key": "CostCenter", "Value": "CC-4521"}]}',
    autoRemediated: true,
    timestamp: '2026-05-22T12:00:00Z',
    success: true,
  },
  {
    id: 'REM-016',
    findingId: 'FINDING-024',
    resourceId: 'arn:aws:rds:us-east-1:123456789012:db:analytics-db',
    resourceType: 'AWS::RDS::DBInstance',
    actionTaken: 'Increased backup retention period from 1 day to 14 days',
    beforeState: '{"BackupRetentionPeriod": 1}',
    afterState: '{"BackupRetentionPeriod": 14}',
    autoRemediated: true,
    timestamp: '2026-05-22T10:00:00Z',
    success: true,
  },
  {
    id: 'REM-017',
    findingId: 'FINDING-014',
    resourceId: 'arn:aws:elasticache:us-east-1:123456789012:replicationgroup:session-cache',
    resourceType: 'AWS::ElastiCache::ReplicationGroup',
    actionTaken: 'Scheduled cluster recreation with in-transit encryption — maintenance window Sunday 02:00 UTC',
    beforeState: '{"TransitEncryptionEnabled": false}',
    afterState: '{"TransitEncryptionEnabled": false, "ScheduledMaintenance": "2026-05-25T02:00:00Z"}',
    autoRemediated: false,
    timestamp: '2026-05-22T08:00:00Z',
    success: true,
  },
  {
    id: 'REM-018',
    findingId: 'FINDING-025',
    resourceId: 'arn:aws:secretsmanager:us-east-1:123456789012:secret:prod/database/master-credentials',
    resourceType: 'AWS::SecretsManager::Secret',
    actionTaken: 'Configured automatic rotation with 30-day schedule using Lambda rotation function',
    beforeState: '{"RotationEnabled": false, "LastRotatedDate": "2026-01-23T00:00:00Z"}',
    afterState: '{"RotationEnabled": true, "RotationLambdaARN": "arn:aws:lambda:us-east-1:123456789012:function:SecretsManagerRotation", "RotationRules": {"AutomaticallyAfterDays": 30}}',
    autoRemediated: false,
    timestamp: '2026-05-22T06:00:00Z',
    success: true,
  },
  {
    id: 'REM-019',
    findingId: 'FINDING-018',
    resourceId: 'arn:aws:s3:::application-logs-archive',
    resourceType: 'AWS::S3::Bucket',
    actionTaken: 'Applied lifecycle policy: transition to IA after 30 days, Glacier after 90 days, expire after 365 days',
    beforeState: '{"LifecycleConfiguration": null}',
    afterState: '{"LifecycleConfiguration": {"Rules": [{"ID": "archive-policy", "Status": "Enabled", "Transitions": [{"Days": 30, "StorageClass": "STANDARD_IA"}, {"Days": 90, "StorageClass": "GLACIER"}], "Expiration": {"Days": 365}}]}}',
    autoRemediated: true,
    timestamp: '2026-05-22T04:00:00Z',
    success: true,
  },
  {
    id: 'REM-020',
    findingId: 'FINDING-021',
    resourceId: 'arn:aws:guardduty:ap-southeast-1:123456789012:detector',
    resourceType: 'AWS::GuardDuty::Detector',
    actionTaken: 'Enabled GuardDuty in ap-southeast-1 with S3 protection and EKS audit log monitoring',
    beforeState: '{"DetectorStatus": "NOT_CONFIGURED"}',
    afterState: '{"DetectorStatus": "ENABLED", "DataSources": {"S3Logs": {"Enable": true}, "Kubernetes": {"AuditLogs": {"Enable": true}}}}',
    autoRemediated: true,
    timestamp: '2026-05-21T22:00:00Z',
    success: true,
  },
];

// --- Trend Data (30 days) ---
function generateTrendData(): TrendDataPoint[] {
  const data: TrendDataPoint[] = [];
  const baseDate = new Date('2026-05-23');

  for (let i = 29; i >= 0; i--) {
    const date = new Date(baseDate);
    date.setDate(date.getDate() - i);
    const dateStr = date.toISOString().split('T')[0];

    // Simulate realistic fluctuation with a slight downward trend for critical
    const dayFactor = (29 - i) / 29;
    data.push({
      date: dateStr,
      critical: Math.max(3, Math.round(8 - dayFactor * 3 + (Math.random() - 0.5) * 2)),
      high: Math.max(5, Math.round(12 - dayFactor * 2 + (Math.random() - 0.5) * 3)),
      medium: Math.round(14 + (Math.random() - 0.5) * 4),
      low: Math.round(8 + (Math.random() - 0.5) * 3),
    });
  }
  return data;
}

export const mockTrendData: TrendDataPoint[] = generateTrendData();

// --- Posture Score ---
export const mockPostureScore: PostureScoreData = {
  score: 73,
  total: 247,
  passing: 180,
  failing: 67,
  byCategory: {
    'Identity & Access Management': { passing: 28, total: 38 },
    'Storage': { passing: 18, total: 25 },
    'Logging & Monitoring': { passing: 22, total: 30 },
    'Networking': { passing: 15, total: 22 },
    'Encryption': { passing: 32, total: 40 },
    'Compute': { passing: 35, total: 42 },
    'Data Protection': { passing: 30, total: 50 },
  },
};

// --- Stat Cards ---
export const mockStatCards: StatCardData[] = [
  { label: 'Critical Findings', value: 5, trend: 2, trendDirection: 'up', icon: '🔴', color: '#ef4444' },
  { label: 'High Findings', value: 8, trend: 1, trendDirection: 'down', icon: '🟠', color: '#f97316' },
  { label: 'Medium Findings', value: 12, trend: 3, trendDirection: 'up', icon: '🟡', color: '#f59e0b' },
  { label: 'Low Findings', value: 7, trend: 2, trendDirection: 'down', icon: '🔵', color: '#3b82f6' },
];
